using System.Collections.Generic;
using Unity.Entities;
using UnityEngine;

/// <summary>
/// 这里只负责预设的转化，数据还是由Hex Grid来提供，后面会迭代由服务器提供数据
/// </summary>
[RequiresEntityConversion]
public class HexMapEntity : MonoBehaviour, IDeclareReferencedPrefabs, IConvertGameObjectToEntity
{
    public List<GameObject> Prefabs;
    
    public void Convert(Entity entity, EntityManager dstManager, GameObjectConversionSystem conversionSystem)
    {
        dstManager.AddComponentData(entity,new Data
        {
            PalmTree=conversionSystem.GetPrimaryEntity(Prefabs[1]),
            Grass= conversionSystem.GetPrimaryEntity(Prefabs[0]),
            Stumb = conversionSystem.GetPrimaryEntity(Prefabs[2]),
            Pine_002_L = conversionSystem.GetPrimaryEntity(Prefabs[3]),
            Pine_002_M2 = conversionSystem.GetPrimaryEntity(Prefabs[4]),
            Pine_002_M3 = conversionSystem.GetPrimaryEntity(Prefabs[5]),
            Pine_002_M = conversionSystem.GetPrimaryEntity(Prefabs[6]),
            Pine_002_S2 = conversionSystem.GetPrimaryEntity(Prefabs[7]),
            Pine_002_U2 = conversionSystem.GetPrimaryEntity(Prefabs[8]),
            Pine_002_U = conversionSystem.GetPrimaryEntity(Prefabs[9]),
            Pine_002_XL = conversionSystem.GetPrimaryEntity(Prefabs[10]),
            Pine_002_XXL = conversionSystem.GetPrimaryEntity(Prefabs[11]),
            Pine_004_01 = conversionSystem.GetPrimaryEntity(Prefabs[12]),
            Pine_004_02 = conversionSystem.GetPrimaryEntity(Prefabs[13]),
            Pine_004_03 = conversionSystem.GetPrimaryEntity(Prefabs[14]),
            Pine_004_04 = conversionSystem.GetPrimaryEntity(Prefabs[15]),
            Pine_004_05 = conversionSystem.GetPrimaryEntity(Prefabs[16]),
            Pine_004_06 = conversionSystem.GetPrimaryEntity(Prefabs[17]),
            Pine_004_Clump01A = conversionSystem.GetPrimaryEntity(Prefabs[18]),
            Pine_004_Clump01B = conversionSystem.GetPrimaryEntity(Prefabs[19]),
            Pine_004_Clump02A = conversionSystem.GetPrimaryEntity(Prefabs[20]),
            Pine_004_Clump02B = conversionSystem.GetPrimaryEntity(Prefabs[21]),
            Pine_004_Clump02C = conversionSystem.GetPrimaryEntity(Prefabs[22]),
            Pine_005_01 = conversionSystem.GetPrimaryEntity(Prefabs[23]),
            Pine_005_02 = conversionSystem.GetPrimaryEntity(Prefabs[24]),
            Pine_006_01 = conversionSystem.GetPrimaryEntity(Prefabs[25]),
            Pine_006_02 = conversionSystem.GetPrimaryEntity(Prefabs[26]),
            Pine_006_03 = conversionSystem.GetPrimaryEntity(Prefabs[27]),
            Pine_006_04 = conversionSystem.GetPrimaryEntity(Prefabs[28]),
            Pine_007_01 = conversionSystem.GetPrimaryEntity(Prefabs[29]),
            Pine_007_RootStump = conversionSystem.GetPrimaryEntity(Prefabs[30]),
            PineDead_02 = conversionSystem.GetPrimaryEntity(Prefabs[31]),
            PineDead_03 = conversionSystem.GetPrimaryEntity(Prefabs[32]),
            TreeDead_01 = conversionSystem.GetPrimaryEntity(Prefabs[33]),
            Broadleaf_Shrub_01_Var1_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[34]),
            Broadleaf_Shrub_01_Var2_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[35]),
            Broadleaf_Shrub_01_Var3_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[36]),
            Broadleaf_Shrub_01_Var4_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[37]),
            Broadleaf_Shrub_01_Var5_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[38]),
            Broadleaf_Shrub_01_Var6_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[39]),
            Bush_Twig_01_Var3_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[40]),
            Bush_Twig_01_Var4_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[41]),
            Clover_01_Var1_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[42]),
            Clover_01_Var2_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[43]),
            Clover_01_Var3_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[44]),
            Clover_01_Var4_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[45]),
            Fern_var01_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[46]),
            Fern_var02_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[47]),
            Fern_var03_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[48]),
            GreenBush_Var01_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[49]),
            Juniper_Bush_01_Var1 = conversionSystem.GetPrimaryEntity(Prefabs[50]),
            Juniper_Bush_01_Var2 = conversionSystem.GetPrimaryEntity(Prefabs[51]),
            Juniper_Bush_01_Var3 = conversionSystem.GetPrimaryEntity(Prefabs[52]),
            Juniper_Bush_01_Var4 = conversionSystem.GetPrimaryEntity(Prefabs[53]),
            Juniper_Bush_01_Var5 = conversionSystem.GetPrimaryEntity(Prefabs[54]),
            Meadow_Grass_01_Var1 = conversionSystem.GetPrimaryEntity(Prefabs[55]),
            Meadow_Grass_01_Var2 = conversionSystem.GetPrimaryEntity(Prefabs[56]),
            Meadow_Grass_01_Var3 = conversionSystem.GetPrimaryEntity(Prefabs[57]),
            Meadow_Grass_01_Var4 = conversionSystem.GetPrimaryEntity(Prefabs[58]),
            Meadow_Grass_01_Var5 = conversionSystem.GetPrimaryEntity(Prefabs[59]),
            Meadow_Grass_01_Var6 = conversionSystem.GetPrimaryEntity(Prefabs[60]),
            PineGroundScatter01_Var1_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[61]),
            PineGroundScatter01_Var2_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[62]),
            RedBush_Var1_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[63]),
            Bush_b1_4x4x4_PF = conversionSystem.GetPrimaryEntity(Prefabs[64]),
            Bush_b1_6x8x6_PF = conversionSystem.GetPrimaryEntity(Prefabs[65]),
            Bush_qilgP2_6x6x4_PF = conversionSystem.GetPrimaryEntity(Prefabs[66]),
            Bush_qilgY2_2x2x4_PF = conversionSystem.GetPrimaryEntity(Prefabs[67]),
            GrassGreen_qheqG2_01 = conversionSystem.GetPrimaryEntity(Prefabs[68]),
            GrassGreen_qheqG2_02 = conversionSystem.GetPrimaryEntity(Prefabs[69]),
            GrassGreen_qheqG2_03 = conversionSystem.GetPrimaryEntity(Prefabs[70]),
            GrassGreen_qheqG2_04 = conversionSystem.GetPrimaryEntity(Prefabs[71]),
            PH_Plant_Perennials_a2_1x1x2_A_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[72]),
            PH_Plant_Perennials_a2_1x1x2_B_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[73]),
            PH_Plant_Perennials_a2_1x1x2_C_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[74]),
            PH_Plant_Perennials_a2_1x1x2_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[75]),
            PH_Plant_Perennials_a4_1x1x0_PF = conversionSystem.GetPrimaryEntity(Prefabs[76]),
            Rock_Granite_rcCwC_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[77]),
            Rock_Granite_reFto_brighter = conversionSystem.GetPrimaryEntity(Prefabs[78]),
            Aset_rock_granite_M_rgAsy = conversionSystem.GetPrimaryEntity(Prefabs[79]),
            Rock_Sandstone_plras = conversionSystem.GetPrimaryEntity(Prefabs[80]),
            Wood_Branch_pjxuR_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[81]),
            Wood_branch_S_pcyeE_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[82]),
            Wood_log_M_qdtdP_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[83]),
            Wood_Log_qdhxa_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[84]),
            Wood_Log_rhfdj = conversionSystem.GetPrimaryEntity(Prefabs[85]),
            Wood_Root_rkswd_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[86]),
            wood_log_M_rfgxx_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[87]),
            Aset_wood_log_M_rfixH_prefab = conversionSystem.GetPrimaryEntity(Prefabs[88]),
            Rock_Passagecave_A = conversionSystem.GetPrimaryEntity(Prefabs[89]),
            FlatRock_01 = conversionSystem.GetPrimaryEntity(Prefabs[90]),
            Rock_06 = conversionSystem.GetPrimaryEntity(Prefabs[91]),
            Rock_06_B = conversionSystem.GetPrimaryEntity(Prefabs[92]),
            Rock_31 = conversionSystem.GetPrimaryEntity(Prefabs[93]),
            Rock_31_B = conversionSystem.GetPrimaryEntity(Prefabs[94]),
            Rock_31_Darker = conversionSystem.GetPrimaryEntity(Prefabs[95]),
            RockSlussen_01 = conversionSystem.GetPrimaryEntity(Prefabs[96]),
            SmallCliff_01_partA = conversionSystem.GetPrimaryEntity(Prefabs[97]),
            SmallCliff_A = conversionSystem.GetPrimaryEntity(Prefabs[98]),
            SmallCliff_A_Brown = conversionSystem.GetPrimaryEntity(Prefabs[99]),
            Cliff_01_Curved_A_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[100]),
            Cliff_01_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[101]),
            HE_bark_strukture_A02_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[102]),
            HE_bark_strukture_A05_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[103]),
            HE_Portal_Modul_A_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[104]),
            HE_Portal_Modul_C_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[105]),
            HE_Portal_Modul_D_Prefab = conversionSystem.GetPrimaryEntity(Prefabs[106]),
            sticks_debris_00_prefab = conversionSystem.GetPrimaryEntity(Prefabs[107]),
            Tree_type_003 = conversionSystem.GetPrimaryEntity(Prefabs[108]),
            Tree_type_004 = conversionSystem.GetPrimaryEntity(Prefabs[109]),
            Tree_type_005 = conversionSystem.GetPrimaryEntity(Prefabs[110]),
            P_OBJ_Bench_01 = conversionSystem.GetPrimaryEntity(Prefabs[111]),
            P_OBJ_flower = conversionSystem.GetPrimaryEntity(Prefabs[112]),
            P_OBJ_fountain_001 = conversionSystem.GetPrimaryEntity(Prefabs[113]),
            P_OBJ_gear_shop = conversionSystem.GetPrimaryEntity(Prefabs[114]),
            P_OBJ_house_001 = conversionSystem.GetPrimaryEntity(Prefabs[115]),
            P_OBJ_house_002 = conversionSystem.GetPrimaryEntity(Prefabs[116]),
            P_OBJ_item_shop = conversionSystem.GetPrimaryEntity(Prefabs[117]),
            P_OBJ_pillar_001 = conversionSystem.GetPrimaryEntity(Prefabs[118]),
            P_OBJ_pillar_002 = conversionSystem.GetPrimaryEntity(Prefabs[119]),
            P_OBJ_pillar_003 = conversionSystem.GetPrimaryEntity(Prefabs[120]),
            P_OBJ_sailboat_01 = conversionSystem.GetPrimaryEntity(Prefabs[121]),
            P_OBJ_sailboat_dock_001 = conversionSystem.GetPrimaryEntity(Prefabs[122]),
            P_OBJ_streetlight_001 = conversionSystem.GetPrimaryEntity(Prefabs[123]),
            P_OBJ_streetlight_002 = conversionSystem.GetPrimaryEntity(Prefabs[124]),
            P_OBJ_streetlight_003 = conversionSystem.GetPrimaryEntity(Prefabs[125]),
            P_OBJ_windmill_01 = conversionSystem.GetPrimaryEntity(Prefabs[126]),
            P_OBJ_windmill_02 = conversionSystem.GetPrimaryEntity(Prefabs[127]),
        });

    }

    public void DeclareReferencedPrefabs(List<GameObject> referencedPrefabs)
    {
        referencedPrefabs.AddRange(Prefabs);
    }

}
